replicaCount: 1

image:
  repository: mocker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

config:
  host: "0.0.0.0"
  port: "8080"
  environment: development
  debug: "false"

ingress:
  enabled: false
  className: ""
  host: mocker.internal
  annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
